
app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/somedb
      username: postgres
      password: 'pass'
      pool-size: 30
#    jpa:
#      hibernate:
#        ddl-auto: update
#
#  jpa:
#    hibernate:
#      ddl-auto: update

server:
  error:
    include-binding-errors: always
    include-message: always