app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/somedb
      username: postgres
      password: 'pass'
      pool-size: 30
  flyway:
    enabled: true

server:
  error:
    include-binding-errors: always
    include-message: always