package com.rifatul.SpringBucks.exception;

public enum ApiErrorCode {
    DUPLICATE_USER,
    EMAIL_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    CARTITEM_NOT_FOUND,
    ORDER_EXPIRED,
    CATEGORY_ID_NOT_FOUND,
    PRODUCT_ID_NOT_FOUND,
    PRICE_INCORRECT_FORMAT,
    PRODUCT_NAME_ALREADY_EXIST,
    PRODUCT_IS_IN_USER_CART,
    PRODUCT_ALREADY_ON_CART
}
